import Head from "next/head";

function Header() {
  return (
    <Head>
      <title>Umibows Blog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Header;